name: Run tests

on:
  push:
  pull_request:
    branches: main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          npm ci
          npm test
