name: Run tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - working-directory: .
        run: |
          npm ci
          npm test
